name: "🚀 Feature Request"
description: "Đề xuất một tính năng mới hoặc cải tiến."
title: "[Feat]: "
labels: ["feature", "enhancement"]

body:
  - type: textarea
    id: feature-description
    attributes:
      label: "💡 Mô tả tính năng"
      description: "Hãy mô tả tính năng mới hoặc tính năng cũ cần cải tiến."
      placeholder: "Viết mô tả ở đây ..."
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: "🎯 Lợi ích & Lý do"
      description: "Tính năng này giải quyết vấn đề gì? Ai sẽ hưởng lợi từ nó?"
      placeholder: "Hãy liệt kê các lợi ích & lý do ở đây ..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: "🛠 Đề xuất cách triển khai"
      description: "Bạn có ý tưởng nào về cách triển khai tính năng này không?"
      placeholder: "Đề xuất cách triển khai ..."
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: "⚡ Mức độ ưu tiên"
      description: "Tính năng này quan trọng như thế nào?"
      options:
        - "🟥 High - Cần gấp"
        - "🟧 Medium - Quan trọng"
        - "🟩 Low - Ý tưởng hay"
    validations:
      required: true

  - type: textarea
    id: additional-info
    attributes:
      label: "📌 Thông tin bổ sung"
      description: "Bất kỳ chi tiết nào khác bạn muốn thêm vào?"
    validations:
      required: false

  - type: checkboxes
    id: confirmation
    attributes:
      label: "✅ Xác nhận"
      options:
        - label: "Tôi đã kiểm tra rằng tính năng này chưa có trong các Issue đã mở."
          required: true
