name: Auto Label "In Progress" on Project Move

on:
  project_card:
    types: [moved]

jobs:
  update_issue_label:
    runs-on: ubuntu-latest
    steps:
      - name: Check issue movement
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const card = context.payload.project_card;
            if (!card.content_url.includes('/issues/')) {
              console.log("Not an issue card, skipping...");
              return;
            }

            const issueNumber = card.content_url.split('/').pop();
            const repo = context.repo;
            const columnName = context.payload.project_card.column_name;

            // Lấy danh sách nhãn hiện tại của issue
            const { data: issue } = await github.rest.issues.get({
              owner: repo.owner,
              repo: repo.repo,
              issue_number: issueNumber
            });

            const labels = issue.labels.map(label => label.name);
            const labelToAdd = "In Progress";
            
            if (columnName === "In progress") {
              // Nếu chuyển vào "In Progress" và chưa có nhãn, thì thêm nhãn
              if (!labels.includes(labelToAdd)) {
                await github.rest.issues.addLabels({
                  owner: repo.owner,
                  repo: repo.repo,
                  issue_number: issueNumber,
                  labels: [labelToAdd]
                });
                console.log(`Added "In Progress" label to issue #${issueNumber}`);
              }
            } else {
              // Nếu chuyển ra khỏi "In Progress" thì gỡ nhãn
              if (labels.includes(labelToAdd)) {
                await github.rest.issues.removeLabel({
                  owner: repo.owner,
                  repo: repo.repo,
                  issue_number: issueNumber,
                  name: labelToAdd
                });
                console.log(`Removed "In Progress" label from issue #${issueNumber}`);
              }
            }
